name: slicing
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/bakso.jpg
  - assets/ayam.jpg
  - assets/nasiGoreng.jpg
  - assets/kentang.jpg
  - assets/jusjambu.png
  - assets/aqua.jpg
  - assets/esteh.png